/*
 * semigroup generated by z^2 and a(z-c)^2+c
 */

#include "../plugin.h"
using namespace QFract;
#include <iostream>
#include <complex>
using namespace std;

const char* NAME = "Semigroup generated by z^2 and a(z-c)^2+c";
const char* CHILD = "";
//const char* COLORMAP = "per2-2.map";
const char* COLORMAP = "default.map";

const double XL = -10.0;
const double YT = 15.0;
const double XR = 20.0;
const double YB = -15.0;

const int MAXITER = 50;
const int MAXORBIT = 10;
const int N = 6;
double VALUE[N]={12.0, 0.0, 1.0, 0.0, 3.5, 0.0};
const Parameter PARAM( N, VALUE );
const char* PARAMDESC[N] = { "Re(c)", "Im(c)", "Re(a)", "Im(a)", "K", "z0/c" };


extern "C" {
int iter(Point z, Parameter param, int max)
{
  complex<double> c(param.Value(0), param.Value(1)),
    a(param.Value(2), param.Value(3)),
    z0(c*param.Value(5)); // z0(0);
  complex<double> x(z.x,z.y), y;
  double R=param.Value(4)*param.Value(4)*norm(c);
  
  register int i;
  int k=0;
  if (norm(x-z0)>=R) return 0;

  for ( i=0; (i<max) && (norm(x-z0) < R ); i++ ) {
    // preserves the value of k when z is in the escaping region
    y=x*x;
    if (norm(y-z0)>= R) {
      y = a*(x-c)*(x-c)+c;
      if (norm(y-z0)< R) {
	k=1;
      }
    } else {
      k=0;
    }
    x = y;
  }

  if (i>=max)
    return -1;

  return i*4 + 21*k+10;
}

Point map(Point z, Point c, Parameter param)
{
  complex<double> d(param.Value(0), param.Value(1)),
    a(param.Value(2), param.Value(3)),
    z0(0);
  complex<double> x(z.x,z.y), y;
  double R=param.Value(4)*param.Value(4)*norm(d);
  
  if (norm(x-z0)>=R) return z;
  
  y=x*x;
  if (norm(y-z0)>= R) {
    y = a*(x-d)*(x-d)+d;
  }
  return Point(real(y),imag(y));
}

Point init(Point c, Parameter param) {return c;}

PluginInfo* getInfo()
{
  PluginInfo* i= new PluginInfo(NAME, XL, YT, XR, YB, MAXITER, MAXORBIT,
				PARAM, CHILD, COLORMAP, PARAMDESC);
  return i;
}
}
